pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                echo env.STAGE_NAME
            }
        }
        stage('test') {
            steps {
                echo env.STAGE_NAME
            }
        }
    }
}
