AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS:Serverless-2016-10-31

Resources:

  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: ex-01-bucket

  MyLambdaExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambda-access-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service: lambda.amazonaws.com
          Action: sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: s3-access
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
              - s3:PutObject
            Resource: '*'

  LogDeliveryLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: lamda-function.lambda_handler
      Runtime: python3.9
      CodeUri: lamda-function.py
      Role: !GetAtt MyLambdaExecutionRole.Arn

  ApiGatewayRestApi:
    Type: AWS::ApiGateway::RestApi
    Properties:
      Name: test-api-gateway

  ApiGatewayResource:
    Type: AWS::ApiGateway::Resource
    Properties:
      RestApiId: !Ref ApiGateway
      PathPart: resource
      ParentId: !GetAtt ApiGateway.RootResourceId

  ApiGatewayMethod:
    Type: AWS::ApiGateway::Method
    Properties:
      RestApiId: !Ref ApiGatewayRestApi
      ResourceId: !Ref ApiGatewayResource
      HttpMethod: POST
      AuthorizationType: NONE
      Integration:
        Type: AWS_PROXY
        IntegrationHttpMethod: POST
        Uri: !Sub
          - >-
            arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFuncNameArn}/invocations
          - LambdaFuncNameArn: !GetAtt LambdaFunction.Arn
      MethodResponses:
      - StatusCode: '200'

  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    DependsOn: ApiGatewayMethod
    Properties:
      RestApiId: !Ref ApiGatewayRestApi

  ApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      FunctionName: !Ref LogDeliveryLambda
      Action: lambda:InvokeFunction
      Principal: apigateway.amazonaws.com

Outputs:
  EndpointURL:
    Description: URL of the endpoint
    Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/ApiGatewayDeployment/resource"
  BucketName:
    Description: Name of the S3 bucket
    Value: !Ref MyBucket